name: Conditional Workflow
on: push

jobs:
   conditional-jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Create Error Type
         run: hebba

       - name: Check and run on faliure
         if: failure()
         run: echo "last job failed"

       -  name: PWD
          run: pwd

       - name: Check and run on suceess
         if: success()
         id: step4
         run: echo "last job sucess"
         
       - name: Evaluate outcome
         if: steps.step4.outcome == 'success'
         run: echo "step4 pass"

   conditional-jobs-on-failure:
     runs-on: ubuntu-latest
     if: failure()
     steps:
       -  name: PWD
          run: pwd

       - name: Check and run on suceess
         if: success()
         id: step4
         run: echo "last job sucess"
         
       - name: Evaluate outcome
         if: steps.step4.outcome == 'success'
         run: echo "step4 pass"
     
