name: Parent Workflow
on: push

jobs:
  childJob: 
    uses: sachinprakash02/github-actions-2025/.github/workflows/child_workflow.yaml@main  
    with:
      logFileName: "hello_child.txt"

  parentJob:
    runs-on: ubuntu-latest
    needs: childJob  
    steps:
      - name: Read output of child job
        run: echo "Child Output ${{ needs.childJob.outputs.logContent }}" 
