name: Parent Workflow
on: push

jobs:
   parentJob:
     runs-on: ubuntu-latest
     outputs: 
      logContent: ${{ needs.childJob.outputs.logContent }}
     steps:
       - name: List file
         run: ls -al

       - name: Call Child Job
         uses: ./.github/workflows/child_wf.yaml
         id: runChild
         with:
            logFileName: "hello_child.txt"
            
       - name: Read output of child job
         run: echo "Child ${{ needs.childJob.outputs.steplogContent }}"
