name : Simple Workflow
on:
    push:
    pull_request:
        types: [opened]
jobs:
    simple-job:
        runs-on : ubuntu-latest
        outputs:
            output_val : ${{steps.step5.outputs.some_var}}
        steps:
            - name: Baby Step
              run: echo "Hello Github Actions"

            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Directory Content
              run: ls -al

            - name: Run Test
              run: python test.py

            - name: Build
              run: python app.py

            - name: Upload artifact
              uses: actions/upload-artifact@v4.6.0
              with:
                  name: build_files
                  path: ./build_log.txt

            - name: Create a output variable
              id: step5
              run: echo 'some_var=some_value' >> $GITHUB_OUTPUT

    next-job:
        runs-on: ubuntu-latest
        needs: simple-job
        env:
            VERSION : "1.2"
        steps:
            - name: Download Artifacts
              uses: actions/download-artifact@v4.1.8
              with:
                  name: build_files

            - name: Show Artifacts
              run: |
                   ls -al
                   cat build_log.txt

            - name: Show output varaibles
              run: echo "${{needs.simple-job.outputs.output_val}}"

            - name: Show Secret Variables
              run: echo "${{secrets.PASSWORD}}"

            - name: Show Variables
              run: echo "${{vars.USERNAME}}"

            - name: Show Environmet Variable
              run: echo "${{env.VERSION}}"

            - name: Show github refs
              run: echo "$GITHUB_REF"

            - name: Add value to a GITHUB_ENV
              run: echo "HOST_IP=10.88.99.11" >> $GITHUB_ENV

            - name: Show github env
              run: echo "$GITHUB_ENV"


                  
                      
              
