name : Simple Workflow
on:
    push:
    pull_request:
        types: [opened]
jobs:
    simple-job:
        runs-on : ubuntu-latest
        steps:
            - name: Baby Step
              run: echo "Hello Github Actions"

            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Directory Content
              run: ls -al

            - name: Run Test
              run: python test.py

            - name: Build
              run: python app.py

            - name: Get artifact
              uses: actions/upload-artifact@v4.6.0
              with:
                  name: build_files
                  path: ./build_log.txt
                      
              
